[db]
path = "/var/lib/corrosion/state.db"
schema_paths = ["/app/schemas"]

[gossip]
# addr should be filled in by entrypoint script
# bootstrap too.
plaintext = true
max_mtu = 1372

[api]
addr = "[::]:8080"

[admin]
path = "/app/admin.sock"

[telemetry]
prometheus.addr = "0.0.0.0:9090"

[log]
colors = false